# Generated by Django 5.0.7 on 2024-07-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('URL (optional)', models.URLField(blank=True)),
                ('Parent (optional)', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menuobject')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menu')),
            ],
        ),
    ]
