# Generated by Django 5.0.7 on 2024-07-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuobject',
            name='Parent (optional)',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menuobject'),
        ),
    ]
