# Generated by Django 5.0.7 on 2024-07-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0002_alter_menuobject_parent_optional_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuobject',
            name='Parent (optional)',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menuobject'),
        ),
        migrations.AlterField(
            model_name='menuobject',
            name='URL (optional)',
            field=models.URLField(blank=True, null=True),
        ),
    ]
