# Generated by Django 5.0.7 on 2024-07-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0004_rename_name_menu_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuobject',
            name='Parent (optional)',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menuobject'),
        ),
        migrations.AlterField(
            model_name='menuobject',
            name='URL (optional)',
            field=models.URLField(null=True),
        ),
    ]
