# Generated by Django 5.0.7 on 2024-07-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0007_rename_parent_optional__menuobject_line_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuobject',
            name='line_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeApp.menuobject'),
        ),
    ]
