# Generated by Django 5.0.7 on 2024-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0008_alter_menuobject_line_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menuobject',
            name='line_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
